name: Publish Docker Image To ECR

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  ECR_AWS_DEFAULT_REGION: us-east-2
  ECR_REGISTRY: 127178877223.dkr.ecr.us-east-2.amazonaws.com

jobs:
  push-docker-image-to-ecr:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::127178877223:role/github/github-truss
          aws-region: ${{ env.ECR_AWS_DEFAULT_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - uses: docker/build-push-action@v6
        env:
          WEBHOOK_TESTER_IMAGE: ${{ env.ECR_REGISTRY }}/webhook-tester
        with:
          file: Dockerfile
          build-args: |
            GIT_HUB_PACKAGES_ACTOR=${{ secrets.GIT_HUB_PACKAGES_ACTOR }}
            GIT_HUB_PACKAGES_TOKEN=${{ secrets.GIT_HUB_PACKAGES_TOKEN }}
          tags: |
            ${{ env.WEBHOOK_TESTER_IMAGE }}:${{ github.sha }}
            ${{ env.WEBHOOK_TESTER_IMAGE }}:latest
          push: true
