name: Publish Bridge Techdocs

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/techdocs.yaml'
      - 'catalog-info.yaml'
      - '**/*.md'
      - 'docs/**'
      - 'mkdocs.yml'
  workflow_dispatch: {}

jobs:
  publish-techdocs:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
        with:
          repository: get-bridge/developer_portal
          token: ${{ secrets.GIT_HUB_TOKEN }}
          path: .github/developer_portal
          ref: master
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::127178877223:role/github/github-truss
          aws-region: us-east-2

      - uses: ./.github/developer_portal/.github/actions/techdocs
        with:
          aws_region: us-east-2
          entity_name: 'webhook-tester'
          entity_kind: 'component'
          entity_namespace: 'default'
